version: '3.8'

services:
  postgresql:
    image: postgres:12.4
    environment:
      POSTGRES_USER: 'task-user'
      POSTGRES_PASSWORD: 'task-pw'
      POSTGRES_DB: 'task'
    ports:
      - '127.0.0.1:10001:5432'
    volumes:
      - ./docker-compose/pginit:/docker-entrypoint-initdb.d
